import { brand } from "../constants/brand";
import { formatDateTimeDisplay, getTimezoneLabel } from "../utils/datetime";

function FooterField({ label, value }) {
  return (
    <div className="receipt-field">
      <div className="receipt-field-label">{label}</div>
      <div className="receipt-field-value">{value}</div>
    </div>
  );
}

export default function ReceiptFooter({ createdAt, exportedAt }) {
  const timezone = getTimezoneLabel(createdAt);

  return (
    <footer className="receipt-section">
      <div className="receipt-footer-grid">
        <FooterField
          label="Record Created"
          value={`${formatDateTimeDisplay(createdAt)} ${timezone}`}
        />
        <FooterField
          label="Exported"
          value={exportedAt ? `${formatDateTimeDisplay(exportedAt)} ${getTimezoneLabel(exportedAt)}` : "Chưa xuất PNG"}
        />
        <FooterField
          label="Generated by"
          value={`${brand.productName} v${brand.productVersion}`}
        />
        <p className="receipt-privacy">Generated locally on the user's device.</p>
      </div>
    </footer>
  );
}
